#!/bin/bash -u

if [[ $TRAVIS_BRANCH =~ ^v[0-9]*$ ]]; then
    last_commit=`git log --oneline -n 1`

    if [[ $last_commit =~ "Cut Release" ]]; then
        echo "Don't do anything else with this commit"
    else
        echo "On a versioned branch and we didn't just cut a release. Preparing a release..."
        ./utils/release prepare
        exit $?
    fi
fi

if [ "${TRAVIS_TAG}" = "${TRAVIS_BRANCH}" ]; then

    if [[ $TRAVIS_BRANCH =~ ^v[0-9]\.[0-9]\.[0-9]$ ]]; then
        echo "On a tag that looks like a version. Releasing..."
        ./utils/release pypi && \
        ./utils/release update-master
        exit $?
    else
        echo "Not on a tag that looks like version. Doing nothing."
        exit 0
    fi

else
    echo "Not a version branch or tag. Doing nothing."
    exit 0
fi