#!/bin/bash -u

docker run -it \
       -e TWINE_USERNAME=${TWINE_USERNAME} \
       -e TWINE_PASSWORD=${TWINE_PASSWORD} \
       -e TWINE_REPOSITORY_URL=${TWINE_REPOSITORY_URL} \
       -e PUBG_CLIENT_GITHUB_TOKEN=${PUBG_CLIENT_GITHUB_TOKEN} \
       -v `pwd`:/package hsenftgrupp/pubg-client-build:0.1.3 release "$@"