#!/bin/bash

docker build -t hsenftgrupp/pubg-client-build:0.1.4 .

docker run -v `pwd`:/package \
       --entrypoint bash \
       hsenftgrupp/pubg-client-build:0.1.4 \
       -c "pip install --upgrade .[dev] > /dev/null && pip freeze" \
       | grep -v pubg-client > dev_requirements.txt